### ISSUE TITLE
Arrow Symbol

### ISSUE THREAD

**Issue by skaman82** [d3ngit/djihdfpv_mavlink_to_msp_V2#1]
Great job on this and Thank you. But why there is an arrow icon here near the VBAT? And why the voltage is shown twice on the screen? I don't own the system yet.
![Bildschirmfoto 2019-12-18 um 10 45 16](https://user-images.githubusercontent.com/11768024/71075077-c18e9200-2183-11ea-90e6-0522fb65dd64.png)

Can it be used do make a proper Home arrow instead of the number?

**Comment by d3ngit** [comment]
No. An arrow it's not possible. We can only use the fields that DJI left available and there is no way to interact with that arrow near the voltage. 
The second voltage can be removed. I accidentally left it in while taking the photo.
