### ISSUE TITLE
RSSI question

### ISSUE THREAD

**Issue by spyder0069** [d3ngit/djihdfpv_mavlink_to_msp_V2#6]
When I start up without the tx on your rssi value is at zero but the osd shows 99.  

Once I power up my crossfire the rssi value goes to 1023.

When I power down the crossfire I get a constant value of 20 and the osd shows 1.

Any input?

**Comment by d3ngit** [comment]
Arupilot sends the rssi number over mavlink in the range of 0-255 and it gets scaled up to 0-1023 in the code to be compatible. I don't know exactly but I have mine set to channel 8 pwm and it auto pulls it from there and displays it in the rssi field.
RSSI_CHANNEL,8
RSSI_TYPE,2

**Comment by spyder0069** [comment]
I have the same setup.  I assume you can reproduce the 99 rssi on powerup with no transmitter on?

My rxrssi in missionplanner shows 0 and again your code shoes zero rssi but it still showed 99 on the osd.  Guessing something with the scaling math going beyond zero or something?

With my crossfire and looking at the channel output with transmitter off (first power on) it doesn't output anything (zero pwm).  Once powered on CH8 goes to 2000.  Then once powered down and it goes into failsafe CH8 goes to 1020.  That is why its showing the 1%.  So that sounds like it would need to be a crossfire fix.

**Comment by spyder0069** [comment]
Maybe your receiver is outputting on CH8 a valid pwm on boot without transmitter powered up so you never saw the 99 issue.  Check your status in planner and see if you are getting ch8 pwm when you first power on.

**Comment by d3ngit** [comment]
99% is normal for 0 on boot, also shows 14 sats when they're 0. This is a dji thing. Do you get the rssi in between or not. I didn't get it.

**Comment by d3ngit** [comment]
This could be a really easy fix if that bothers you, just put 1 instead of 0 as the default rssi variable. uint16_t rssi = 0;

**Comment by spyder0069** [comment]
Still had the 1% after that change.  Its not a big deal just didn't know if anyone had mentioned it and figured I would give some feedback.  :^)

**Comment by spyder0069** [comment]
You can close this if that is expected behavior.   Thanks!

**Comment by d3ngit** [comment]
Ok. It's not a problem if it works as expected when you fly. On boot anything can happen with default values.
