### ISSUE TITLE
Map Throttle Position to unused element

### ISSUE THREAD

**Issue by FranzAr** [d3ngit/djihdfpv_mavlink_to_msp_V2#7]
Hi, I'd really like to see my throttle position in the OSD.
Would it be possible to map it to an unused element.
I played around a bit and found out that DISARMED, FLYMODE (already toggling with Alt/Speed), MAIN BATTERY VOLTAGE are working  and not really used.
Greets
Franz

**Comment by d3ngit** [comment]
This would be pretty easy to do. I'll look at it today. what about the main_batt_usage, looks like a slider, or the roll/pitch pids but in the range of 0%-100%. You need it in percents or PWM values?

**Comment by FranzAr** [comment]
Percentage would be great. Element of your choice ;-) Thanks mate!

**Comment by d3ngit** [comment]
I have it already working with the ROLL pid element and it's working fine. I'll just do a few more tests in the simulator and update the code soon.

**Comment by d3ngit** [comment]
Done.

**Comment by FranzAr** [comment]
Thanks mate! I'll check that out tonight :-)

**Comment by FranzAr** [comment]
Can confirm, works like a charm. Thanks
